### ISSUE TITLE
Fehler nach Update auf 1.21.1

### ISSUE THREAD

**Issue by falkgeist** [heimrichhannot/contao-tiny-slider-bundle#12]
Nach dem Update auf 1.21.1 wurde ein Fehler angezeigt, dass der Zugriff auf den container nicht möglich ist.

Ich vermute der Fehler kommt hierher:
https://github.com/heimrichhannot/contao-tiny-slider-bundle/blob/17f57925824b47fa392bd8cd13b010d4a9b7f36e/src/Element/ContentStart.php#L29C13-L29C76
bzw
https://github.com/heimrichhannot/contao-tiny-slider-bundle/blob/f3fe4616f8a0cff1fd031d315b099786f6d293a5/src/Element/ContentStart.php#L30

Da scheint was mit dem Utils bundle nicht ganz sauber zu laufen.

Wenn ich dazu komme, teste ich das nochmal, hatte das in dem System jetzt erstmal wieder auf die vorige Version zurückgestellt.

**Comment by koertho** [comment]
@falkgeist Hi, danke für deine Meldung. Bitte immer Contao- und PHP-Version mit angeben und am besten einen Screenshot der Fehlermeldung im Dev-Modus. Die Fehlerbeschreibung ist leider so leider nicht sehr aussagekräftig.

**Comment by derkosmonaut** [comment]
Hey, bei mir gerade das gleiche Problem.  (C: 4.13.35 / PHP 8.1.26)

`request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function isBackend() on null" at /usr/www/****/vendor/heimrichhannot/contao-tiny-slider-bundle/src/Element/ContentStart.php line 30 {"exception":"[object] (Error(code: 0): Call to a member function isBackend() on null at /usr/www/****/vendor/heimrichhannot/contao-tiny-slider-bundle/src/Element/ContentStart.php:30)"} []`

**Comment by koertho** [comment]
Testet mal bitte, ob es als Workaround reicht, das Utils-bundle zu updaten.

**Comment by koertho** [comment]
Ok, war ein kleiner Syntax-Error drin, ist behoben. Danke fürs melden!
