### ISSUE TITLE
Kompatibilität zu symfony/framework-bundle 4.*?

### ISSUE THREAD

**Issue by rustykowski** [heimrichhannot/contao-tiny-slider-bundle#4]
Zur Zeit ist die Abhängigkeit auf symfony/framework-bundle: ^3.4 eingestellt.
Dadurch lässt sich das Paket nicht unter Contao 4.8 installieren (symfony/framework-bundle4.2.* || 4.3.*).
Lässt sich die Abhängigkeit entsprechend erweitern?

**Comment by koertho** [comment]
@rustykowski Ich versuche es die nächsten Tage mit einzutakten.

**Comment by rustykowski** [comment]
Prima, danke!

**Comment by koertho** [comment]
@rustykowski habe ich dependency in 1.10.2 entfernt. Ich kann aber keine Garantie geben, dass es dann unter Symfony 4 läuft. Das Bundle ist schon etwas älter.

**Comment by rustykowski** [comment]
Vielen Dank, @koertho! Das Paket lässt sich installieren und im Backend bedienen. 
Im Quelltext wird auch ein `<div class="tiny-slider-container"  data-tiny-slider-config="...">` ausgegeben. Allerdings wird kein Script geladen und auch nichts initialisiert.
Ich hatte diese Erweiterung allerdings auch noch nie im Einsatz. Es kann also sein, dass ich irgendwo etwas Zentrales übersehen habe.

**Comment by koertho** [comment]
@rustykowski Danke für die Rückmeldung. 
Rein theoretisch sollte es out-of-the-box funktionieren, aber wir setzen es selbst nur in Verbindung mit Contao 4.4 und dem Encore-Bundle ein. Bitte erstelle ein neues Issue mit der Fehlerbeschreibung und wie du vorgegangen bist und ich schaue mal, ob ich es beheben kann.
